extends Node

enum { DIRECTION_UP, DIRECTION_DOWN, DIRECTION_LEFT, DIRECTION_RIGHT }
enum {
	ANIMATION_IDLE,
	ANIMATION_WALK,
	ANIMATION_HACK,
	ANIMATION_SLASH,
	ANIMATION_CAST,
	ANIMATION_DIE
}

enum { ENTITY_ALIVE, ENTITY_DEAD }

enum { SCENE_TEST_MAP, SCENE_CREATE_CHARACTER }

enum { GENDER_MALE, GENDER_FEMALE }
